In [23]:
import numpy as np
import pandas as pd


In [24]:
df=pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233  1.0        0      150      0      2.3   
1     37    1   2       130   250  0.0        1      187      0      3.5   
2     41    0   1       130   204  0.0        0      172      0      1.4   
3     56    1   1       120   236  0.0        1      178      0      0.8   
4     57    0   0       120   354  0.0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241  0.0        1      123      1      0.2   
299   45    1   3       110   264  0.0        1      132      0      1.2   
300   68    1   0       144   193  1.0        1      141      0      3.4   
301   57    1   0       130   131  0.0        1      115      1      1.2   
302   57    0   1       130   236  0.0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0   1.0       1  
1        0   0   2.0       1  
2        2   0   2.0       1  
3        2   0   2.0       1  
4        2   0   2.0       1  
..     ...  ..   ...     ...  
298      1   0   3.0       0  
299      1   0   3.0       0  
300      1   2   3.0       0  
301      1   1   3.0       0  
302      1   1   2.0       0  

[303 rows x 14 columns]

In [33]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         5
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        6
target      0
dtype: int64

In [35]:
df.fillna(0, inplace=True)


In [36]:
df.target.value_counts()

1    165
0    138
Name: target, dtype: int64

In [37]:
x=df.iloc[:,0:-1]
x.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233  1.0        0      150      0      2.3      0   
1   37    1   2       130   250  0.0        1      187      0      3.5      0   

   ca  thal  
0   0   1.0  
1   0   2.0

In [38]:
y=df.iloc[:,-1]
y.head(2)

0    1
1    1
Name: target, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [40]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [41]:
from sklearn.naive_bayes import GaussianNB

In [42]:
model=GaussianNB()

In [43]:
model_train=model.fit(x_train,y_train)

In [45]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [47]:
y_test.values

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [51]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[27,  2],
       [ 5, 27]], dtype=int64)

In [54]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.8852459016393442

In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.93      0.89        29
           1       0.93      0.84      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61

